### ISSUE TITLE
torch and sklearn optional

### ISSUE THREAD

**Issue by isabelizimm** [tidymodels/vetiver-python#21]

**Comment by machow** [comment]
Hey--looking at a similar thing in py-shiny, I'm noticing they're doing something like this...

```python
import sys

def create_translator(model, ptype_data, save_ptype):
    if "torch" in sys.modules:
        from torch import nn
        if isinstance(model, nn.Model):
            ...
    elif "sklearn" in sys.modules:
        from sklearn.base import BaseEstimator
        if isinstance(model, BaseEstimator):
            ...
```

**Comment by isabelizimm** [comment]
If the model comes from torch, torch would have been imported. 

This is a more lightweight check than attempting to import, so less compute heavy.

**Comment by has2k1** [comment]
> ```python
>     if "torch" in sys.modules:
>         from torch import nn
>         if isinstance(model, nn.Model):
> ```

This is does something entirely different. [sys.modules](https://docs.python.org/3/library/sys.html#sys.modules) contains modules that have been loaded i.e imported somewhere. e.g. if you import pandas, it run `pandas/__init__.py` and some of the modules imported in there should import numpy; and now 'numpy` will be in your `sys.modules`.

```python
>> python
Python 3.10.2 (main, Feb 14 2022, 13:00:18) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> 'numpy' in sys.modules
False
>>> import pandas as pd
>>> 'numpy' in sys.modules
True
```

So if you assume that at that point a user should have imported something to do with `torch` or `sklearn` in their user-land code, then  you can check `sys.modules`.

**Comment by isabelizimm** [comment]
Thank you both for giving context on different ways to make `torch` an optional dependency! I ended up going with the 

```
torch_exists = True
try:
    import torch
except ImportError:
    torch_exists = False
```


method, to specifically check if a module _can be installed,_ rather than if it has already been imported. (For my own future reference, the second answer on [this stackexchange question](https://askubuntu.com/questions/588390/how-do-i-check-whether-a-module-is-installed-in-python-and-install-it-if-needed) also gives a good explanation of this!)

**Comment by machow** [comment]
Hey--if I understand the problem correctly, you are receiving some object `model`, and need to determine whether it inherited from something within a specific package.

I def think try/except is a little funky here (since as you add adaptors you will need to import all their adapted libraries), but AFAIK there is 1 case try/except will get sys.modules won't-- metaclasses that override [`__instancecheck__`](https://docs.python.org/3/reference/datamodel.html#class.__instancecheck__) -- so at the very least try/except seems like the most thorough..!
